### ISSUE TITLE
Power state not updating 

### ISSUE THREAD

**Issue by Flash-28** [jdtsmith/homebridge-denonmarantzavr#6]
If you turn the receiver on outside of this Homebridge plugin and then want to turn off the receiver using the homekit switch, the app shows that the receiver is off.  Looking at the console, it queries the power state through "ZM Status GET:" when you look at the plugin through homekit app, but returns "false".  Turning the zone on through homekit results in a "no response" error, but after a couple tries it will eventually allow you to set the state to on and then off.  Looks like the logic or timing for checking status is not working as expected.

**Comment by Flash-28** [comment]
I find that if I wait some time (minutes) then checking the status of the power eventually updates correctly.  So I think there is a timing issue.  BTW, my testing is on a Denon X6200W receiver.

**Comment by jdtsmith** [comment]
There is only one shared network connection to each AVR.  Did you follow the homebridge logs to see what status messages this plugin receives from the AVR while you are controlling it outside of HomeKit?  Any other activity which turns your AVR zones on, main or otherwise, should show up as `ZMON`, `Z2ON`, and that's what this plugin us looking for.   There is no timing involved, but for me status update is instant for either zone. 

If you don't have debugging enabled by default, you can use `DEBUG=* homebridge`.  I have homebridge as a service, so `journalctl -fu homebridge` gives all the received data under 'Status: '. In that case you may need to add `DEBUG=*` to your `/etc/default/homebridge`.
